name: Output Info Demo
on:
  push: # event
    branches: # activites
      - main
      - new_branch
    paths-ignore:
     - '.github/workflows/*'

jobs:
  display_info:
    runs-on: ubuntu-latest
    steps:
      - name: Show Some Info
        run: echo "${{ toJSON(github)}}"